development:
  SoundCloudClientId: xxx
  SoundCloudClientSecret: xxx
  BlogTitel: Music Blog
  User: 
  Pass: 
production:
  SoundCloudClientId: xxx
  SoundCloudClientSecret: xxx
  BlogTitel: Music Blog
  User: 
  Pass: 