development:
  SoundCloudClientId: xxx
  SoundCloudClientSecret: xxx
  BlogTitel: Music Blog
  User: 
  Pass: 
production:
  SoundCloudClientId: xxx
  SoundCloudClientSecret: xxx
  BlogTitel: Music Blog
  User: test
  Pass: ChangeMe
  MongoUser: user
  MongoPass: pass
  MongoPort: 20543